### ISSUE TITLE
put "password" in POST /messages

### ISSUE THREAD

**Issue by shokai** [shokai/ruby-irkit#8]
[IRKitの脆弱性とファームウェアアップデートのお願い - maaash.jp](http://maaash.jp/2015/09/irkit-firmware-update/)

> POST /messages のAPIのみ、赤外線信号を表すJSONに以下のように、IRKitがWi-Fiアクセスポイントになる際のパスワードを追加し、X-Requested-With ヘッダを付けないで送信してください。
{"format":"raw","freq":38,"data":[18031,8755,...省略...4400,1190],"password":"XXXXXXXXXX"}

http://getirkit.com/#IRKit-Device-POST-messages

Internet-API does not require it.

**Comment by shokai** [comment]
#7

**Comment by shokai** [comment]
これ、ブラウザから送信する時のみ必要なのかも？

**Comment by mash** [comment]
そうです。ブラウザからIRKitにリクエストを投げていたアプリケーションを、最小の変更（passwordの追加）で救おうとする救済措置です。

**Comment by shokai** [comment]
なるほど
